### ISSUE TITLE
Flickrnode should be able to make many requests at once

### ISSUE THREAD

**Issue by ncr** [ciaranj/flickrnode#1]
I would like to be able to choose either a http client pool size (so all requests use http clients from this pool) OR make every request spawn a separate http client (this would let me directly control the amount of simultaneous requests). I think both options would be great - use predefined client pool for quick jobs or have a fine grained control when you need it.

Cheers,

Jacek

**Comment by ciaranj** [comment]
This should now be fixed in http://github.com/ciaranj/flickrnode/commit/56ba2679dd795f29f07380ae813f2b7c84d35c9a    I had thought the http client would automatically pipeline my requests (as the same host is being used.)  However the node.js documentation does suggest that this is not implemented, now it will create a connection per api request.  I've factored off the connection creation so we could move it to a pool based/configurable approach in the future.
